python ../src/proximal-policy-optimization/proximal_policy_optimization.py \
--env CartPole-v0 \
--hidden_sizes 64 64 \
--activations relu relu relu \
--gamma 0.99 \
--clip_ratio 0.3 \
--seed 0 \
--steps 4000 \
--epochs 100 \
--pi_lr 3e-3 \
--v_lr 1e-2 \
--value_func_iters 80 \
--train_pi_iters 80 \
--lamb 0.97 \
--max_episode_length 1000 \
--target_kl 0.03 \